spring:
    profiles: desa
name: desa-YAML
environment: desa
servers: 
    - www.abc.desa.com
    - www.xyz.desa.com
 
---
spring:
    profiles: prod
name: prod-YAML
environment: production
servers: 
    - www.abc.com
    - www.xyz.com