base:
  rest:
    scheme: http
    domain: localhost
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
#  level:
#    org.springframework: INFO
#    org.hibernate: DEBUG

urls:
  front: ${base.rest.scheme}://${base.rest.domain}
  
eureka:
  instance:
    metadata-map:
      management:
        port: 9090